import "./globals.css";
import { Roboto } from "next/font/google";
import Header from "./components/Header";
import Footer from "./components/Footer";
import logo from "../public/images/logoFUMELI 1.png";

export const metadata = {
  title: "Fumeli App",
  description: "Generated by create next app",
  icon: { logo },
};

const roboto = Roboto({
  weight: ["400", "700"],
  subsets: ["latin"],
});

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <main
          className={`bg-[#19181C] min-h-screen w-screen ${roboto.className} overflow-hidden`}
        >
          <Header />
          {children}
          <Footer />
        </main>
      </body>
    </html>
  );
}
